# Generated by Django 4.0.6 on 2022-07-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descripton',
            new_name='description',
        ),
    ]
